@BookTracker.Api_HostAddress = http://localhost:5125



### Get Books
GET http://localhost:5125/books

### Get Books Page 1
GET http://localhost:5125/books?page=1&pageSize=10

### Get Books Page 2
GET http://localhost:5125/books?page=2&pageSize=10

### Search Books
GET http://localhost:5125/books?search=octopus

### Search Books With Paging
GET http://localhost:5125/books?search=octopus&page=1&pageSize=5

### Create Book
POST http://localhost:5125/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE http://localhost:5125/books/1

### Update Book
PUT http://localhost:5125/books/2
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

### Get Book by Id
GET http://localhost:5125/books/1

### Get Members
GET http://localhost:5125/members

### Create Member With Credentials
POST http://localhost:5125/members
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@example.com",
  "password": "analytical-engine"
}

### Get Member Details
GET http://localhost:5125/members/1

### Update Member
PUT http://localhost:5125/members/1
Content-Type: application/json

{
  "name": "Ada Byron",
  "email": "ada.byron@example.com"
}

### Delete Member
DELETE http://localhost:5125/members/1


